name: Make

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      TERM: xterm

    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make debug
      - name: tests
        run: make test
