name: Make

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      TERM: xterm
      GITHUB: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
      - name: Build code
        run: make debug
      - name: Check tests
        run: make valgrindtest
